### ISSUE TITLE
Perhaps CONS-Dfam_3.2 missing from container?

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Dfam-consortium/TETools#6] opened 2020-11-10 20:48 UTC
**Describe the bug**
Not sure, but maybe the RepeatMasker Libraries directory is missing a file/dir like CONS-Dfam_3.2?  Should this work, or is it misguided?

**To Reproduce**
Using LIBDIR, which is simply a writable, private copy of /opt/RepeatMasker/Libraries.  The command seems to fail because it's trying to access Libraries files it expects, but which do not exist.

```
$ LIBDIR=/projects/hpcrcf/mcolema5/mcurrey-repeatmasker/Libraries  singularity exec --
bind=/projects,/packages docker://dfam/tetools:1.2 RepeatMasker  -species liliopsida empty.fa
RepeatMasker version 4.1.1
Search Engine: NCBI/RMBLAST [ 2.10.0+ ]

Using Master RepeatMasker Database: /projects/hpcrcf/mcolema5/mcurrey-repeatmasker/Libraries/RepeatMaskerLib.h5
  Title    : Dfam
  Version  : 3.2
  Date     : 2020-07-02
  Families : 6,953

Species/Taxa Search:
  Liliopsida [NCBI Taxonomy ID: 4447]
  Lineage: root;cellular organisms;Eukaryota;Viridiplantae;
           Streptophyta;Streptophytina;Embryophyta;Tracheophyta
  9 families in ancestor taxa; 0 lineage-specific families

Building general libraries in: /projects/hpcrcf/mcolema5/mcurrey-repeatmasker/Libraries/CONS-Dfam_3.2/general
RepeatMasker::createLib(): Error invoking /opt/rmblast/bin/makeblastdb on file /projects/hpcrcf/mcolema5/mcurrey-repeatmasker/Libraries/CONS-Dfam_3.2/general
/is.lib.

```

**Expected behavior**
Not very familiar with RM, but was expecting it to try to extract/build the sub-library for the named species.  ??

Alternatively, is there any reasonably simple way to add this to my writable copy?

**Host system (please complete as much of the following information as you can find out):**
 - RHEL 7.8
 - Singularity 3.3.0-1
 - Container image 1.2  (same behavior with latest)

**Comment by jebrosen** [comment] 2020-11-11 05:11
> Not sure, but maybe the RepeatMasker Libraries directory is missing a file/dir like CONS-Dfam_3.2? Should this work, or is it misguided?

It's not missing! The directory should be generated on an as-needed basis, by default in `Libraries/` if it is writable, or in a directory under `$HOME` if `Libraries` is readonly.

```
Building general libraries in: /projects/hpcrcf/mcolema5/mcurrey-repeatmasker/Libraries/CONS-Dfam_3.2/general
RepeatMasker::createLib(): Error invoking /opt/rmblast/bin/makeblastdb on file /projects/hpcrcf/mcolema5/mcurrey-repeatmasker/Libraries/CONS-Dfam_3.2/general
/is.lib.
```

From around this time there should be a log file named `rmblast.log`, in that `general/` directory. Could you paste or attach the contents of that file? It might have a more specific or informative error.

**Comment by michaelkarlcoleman** [comment] 2020-11-12 19:35
Thanks, that was very helpful.  Here was what was in that log:
```
New DB name:   /projects/hpcrcf/mcolema5/mcurrey-repeatmasker/Libraries/CONS-Dfam_3.2/general/is.lib
New DB title:  /projects/hpcrcf/mcolema5/mcurrey-repeatmasker/Libraries/CONS-Dfam_3.2/general/is.lib
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /projects/hpcrcf/mcolema5/mcurrey-repeatmasker/Libraries/CONS-Dfam_3.2/general/is.lib
Keep MBits: T
Maximum file size: 1000000000B

No volumes were created.

Error: mdb_env_open: Cannot allocate memory
```
Looking around, this appears to be similar to this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960756
In particular, it seems plausible that this is an `mmap` call failing.  The 'ulimit -v' was set to about 48GB, but apparently that wasn't enough.  Retrying with 'unlimited' seemed to get it working.

Appreciate your help!

P.S.  Would be handy to have `strace` in that container, for debugging.

**Comment by jebrosen** [comment] 2021-01-16 03:23
Glad to hear you found the cause - and thanks for that link. Apparently `-blastdb_version 4` is a potential workaround for this issue in the debian bug report, which I'll consider adding to `RepeatMasker` itself - we have seen other issues with the version 5 databases in other contexts as well.

I have also added `strace` to the container starting in [`1.3-beta-1`](https://github.com/Dfam-consortium/TETools/blob/1.3-beta-1/CHANGELOG.md#13-beta-1---2021-01-15), so I'm closing this issue. Thanks for the report!

**Closed by jebrosen** 2021-01-16 03:23 UTC
Labels: upstream
