### ISSUE TITLE
RepeatMasker "forksys: Program terminated by a signal 7"

### ISSUE THREAD

**Issue by R-Huerlimann** [Dfam-consortium/TETools#4] opened 2020-03-10 22:52 UTC
Hi all,

I'm running RepeatMasker using TETools through the singularity wrapper script. And it seems to be terminating at the same spot. I get the following error message while it is generating the output:

`forksys:  Program terminated by a signal 7.
The executing command was:  /opt/RepeatMasker/ProcessRepeats -lib consensi.fa.classified -gff -poly -u -source -html -xm -orifile assembly_v1.0.fasta -maskSource /home/roger/Analysis/Assembly_v1.0/RM_1798.MonMar92212332020/assembly_v1.0.fasta -xsmall /home/roger/Analysis/Assembly_v1.0/RM_1798.MonMar92212332020/assembly_v1.0.fasta.cat.gz`

I'm using this command:
`RepeatMasker -pa 30 -gff -html -xsmall -lib consensi.fa.classified -xm -u -poly -q -source assembly_v1.0.fasta`

any ideas what the problem could be?

**Comment by jebrosen** [comment] 2020-03-11 17:43
Can you also report your kernel version / operating system distribution (`uname -a`)?

Signal 7 on linux is `SIGBUS`, which indicates a memory access error. It is unusual that it would happen from `ProcessRepeats`, which is a perl script.

Luckily `ProcessRepeats` is the last step, so nothing significant has been lost. I first suggest manually re-running that `/opt/RepeatMasker/ProcessRepeats -lib consensi.fa.classified -gff -poly ...` command again in case it was a spurious error.

**Comment by R-Huerlimann** [comment] 2020-03-11 22:09
Kernel version: Linux version 4.15.0-88-generic (buildd@lgw01-amd64-036) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020

Manually re-running the ProcessRepeats step did the trick. I've run the whole pipeline three times, with some modified parameters, and error happened every time. I also used conda to install RepeatModeler that way, and reran RepeatMasker, and the same error occurs.

At least I have a workaround now! Thank you!

**Comment by jebrosen** [comment] 2020-03-11 22:14
Come to think of it, I believe that error *can* also be caused by running out of memory. If you do further runs of RepeatModeler it would be a good idea to watch the memory usage and make sure you are safely under available memory / limits.

Closing for now, until there is enough information to reproduce or trace a cause.

**Closed by jebrosen** 2020-03-11 22:14 UTC
Labels: upstream
